services:
  - type: web
    name: music-library-api
    runtime: docker
    buildCommand: docker build -t music-library-api .
    startCommand: docker run -p 8080:8080 music-library-api
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    plan: free
