spring:
  application:
    name: MusicLibrary

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music_library_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 8 dialect for Hibernate


  jedis:
    pool:
      max-idle: 10
      min-idle: 1
      max-active: 10
      max-wait: 2000

  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      timeout: 2000

  sql:
    init:
      mode: always
logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        orm: DEBUG