
spring:
  application:
    name: MusicLibrary

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music_library_db
    username: 'root'
    password: 'password'
    hikari:
      connection-timeout: 30000                  # Timeout for acquiring a connection (30 seconds)
      maximum-pool-size: 10                       # Maximum pool size
      minimum-idle: 5                             # Minimum idle connections in the pool
      idle-timeout: 600000                        # Maximum time an idle connection is kept in the pool (10 minutes)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL8Dialect'

  jedis:
    pool:
      max-idle: 10
      min-idle: 1
      max-active: 10
      max-wait: 2000
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      timeout: 2000
  sql:
    init:
      mode: always
