
spring:
  application:
    name: MusicLibrary
  security:
    user:
      name: admin
      password: admin

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music_library_db
    username: 'root'
    password: 'password'
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL8Dialect'

  jedis:
    pool:
      max-idle: 10
      min-idle: 1
      max-active: 10
      max-wait: 2000
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      timeout: 2000
